/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/intake/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job From Document */
        post: operations["create_job_from_document_api_intake_document_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Calls */
        post: operations["start_calls_api_jobs__job_id__calls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Job */
        post: operations["confirm_job_api_jobs__job_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Events */
        get: operations["get_job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/negotiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Negotiate */
        post: operations["negotiate_api_jobs__job_id__negotiate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_jobs__job_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover Vendors */
        get: operations["discover_vendors_api_vendors_discover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/elevenlabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Elevenlabs Webhook */
        post: operations["elevenlabs_webhook_api_webhooks_elevenlabs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmountStatus
         * @enum {string}
         */
        AmountStatus: "known" | "unknown" | "not_applicable";
        /**
         * AvailabilityStatus
         * @enum {string}
         */
        AvailabilityStatus: "available" | "unavailable" | "unknown";
        /**
         * BindingType
         * @enum {string}
         */
        BindingType: "binding" | "non_binding" | "unknown";
        /** CallOutcome */
        CallOutcome: {
            /** Callback At */
            callback_at?: string | null;
            quote?: components["schemas"]["QuoteV1"] | null;
            /** Reason */
            reason?: string | null;
            type: components["schemas"]["CallOutcomeType"];
        };
        /**
         * CallOutcomeType
         * @enum {string}
         */
        CallOutcomeType: "itemized_quote" | "callback_commitment" | "documented_decline" | "failed";
        /** CallRecord */
        CallRecord: {
            /**
             * Call Id
             * Format: uuid
             */
            call_id: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            outcome: components["schemas"]["CallOutcome"];
            /**
             * Recording Url
             * Format: uri
             */
            recording_url: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["CallStatus"];
            vendor: components["schemas"]["Vendor"];
        };
        /**
         * CallStatus
         * @enum {string}
         */
        CallStatus: "pending" | "in_progress" | "completed" | "failed";
        /**
         * DataClassification
         * @enum {string}
         */
        DataClassification: "synthetic" | "role_play" | "real_redacted";
        /**
         * DocumentIntakeRequest
         * @description Bound the unstructured document text accepted by the intake route.
         */
        DocumentIntakeRequest: {
            /** Document Text */
            document_text: string;
        };
        /**
         * DwellingType
         * @enum {string}
         */
        DwellingType: "apartment" | "condo" | "townhouse" | "house" | "storage_unit" | "other";
        /**
         * ElevenLabsPostCallWebhook
         * @description Typed public shape for the ElevenLabs post-call webhook.
         */
        ElevenLabsPostCallWebhook: {
            data: components["schemas"]["PostCallWebhookData"];
            /** Event Timestamp */
            event_timestamp: number;
            /**
             * Type
             * @constant
             */
            type: "post_call_transcription";
        } & {
            [key: string]: unknown;
        };
        /** ElevenLabsWebhookEvent */
        ElevenLabsWebhookEvent: {
            /** Call Id */
            call_id?: string | null;
            /** Event Type */
            event_type: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * FeeCategory
         * @enum {string}
         */
        FeeCategory: "base_service" | "hourly_minimum" | "travel" | "fuel" | "stairs" | "elevator" | "long_carry" | "packing" | "materials" | "disassembly" | "storage" | "insurance" | "tax" | "deposit" | "other";
        /** FeeLineItem */
        FeeLineItem: {
            /** Amount */
            amount?: string | null;
            /** @default known */
            amount_status: components["schemas"]["AmountStatus"];
            category: components["schemas"]["FeeCategory"];
            /** Description */
            description: string;
            /**
             * Disclosed Upfront
             * @default true
             */
            disclosed_upfront: boolean;
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * Mandatory
             * @default false
             */
            mandatory: boolean;
            /** Minimum Units */
            minimum_units?: string | null;
            /** Unit Rate */
            unit_rate?: string | null;
            /** Units */
            units?: string | null;
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "info" | "warning" | "critical";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Mode
             * @default mock
             * @constant
             */
            mode: "mock";
            /**
             * Service
             * @default veramove-api
             * @constant
             */
            service: "veramove-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * IntakeSource
         * @enum {string}
         */
        IntakeSource: "voice" | "document" | "merged" | "demo";
        /** IntelligenceFinding */
        IntelligenceFinding: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /**
             * Deterministic
             * @default true
             */
            deterministic: boolean;
            /** Evidence Ids */
            evidence_ids?: string[];
            fee_category?: components["schemas"]["FeeCategory"] | null;
            /** Quote Id */
            quote_id?: string | null;
            severity: components["schemas"]["FindingSeverity"];
            /** Vendor Id */
            vendor_id?: string | null;
        };
        /** InventoryItem */
        InventoryItem: {
            /**
             * Fragile
             * @default false
             */
            fragile: boolean;
            /**
             * Item Id
             * Format: uuid
             */
            item_id?: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Oversized
             * @default false
             */
            oversized: boolean;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Room */
            room: string;
        };
        /**
         * JobEvent
         * @description Safe provider-neutral event exposed by orchestration.
         */
        JobEvent: {
            /** Call Id */
            call_id?: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id?: string;
            /** Event Type */
            event_type: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Metadata */
            metadata?: {
                [key: string]: string | number | boolean | null;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * JobEventsResponse
         * @description Envelope safe normalized events for a single job.
         */
        JobEventsResponse: {
            /** Events */
            events: components["schemas"]["JobEvent"][];
        };
        /** JobRecord */
        JobRecord: {
            /** Calls */
            calls?: components["schemas"]["CallRecord"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            job_spec: components["schemas"]["JobSpecV1"];
            /** Quotes */
            quotes?: components["schemas"]["QuoteV1"][];
            recommendation?: components["schemas"]["RecommendationV1"] | null;
            state: components["schemas"]["JobState"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobSpecV1 */
        JobSpecV1: {
            /** Bedroom Count */
            bedroom_count?: number | null;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Confirmed At */
            confirmed_at?: string | null;
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** Date Flexible */
            date_flexible?: boolean | null;
            destination: components["schemas"]["OriginDestinationAccess"];
            /** Insurance Preference */
            insurance_preference?: string | null;
            intake_source: components["schemas"]["IntakeSource"];
            /** Inventory */
            inventory?: components["schemas"]["InventoryItem"][];
            /**
             * Job Id
             * Format: uuid
             */
            job_id?: string;
            /** Locked Version */
            locked_version?: "1.0" | null;
            /** Move Date */
            move_date?: string | null;
            origin: components["schemas"]["OriginDestinationAccess"];
            /** Oversized Or Fragile Items */
            oversized_or_fragile_items?: string[];
            services?: components["schemas"]["MovingServices"];
            source_context?: components["schemas"]["SourceContext"];
            /**
             * Version
             * @default 1.0
             * @constant
             */
            version: "1.0";
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "draft" | "intake_complete" | "confirmed" | "calling" | "quotes_ready" | "negotiating" | "completed" | "failed";
        /** MovingServices */
        MovingServices: {
            /** Disassembly */
            disassembly?: boolean | null;
            /** Packing */
            packing?: boolean | null;
            /** Storage */
            storage?: boolean | null;
            /** Storage Days */
            storage_days?: number | null;
        };
        /** OriginDestinationAccess */
        OriginDestinationAccess: {
            /** Access Notes */
            access_notes?: string | null;
            /** Address Summary */
            address_summary?: string | null;
            dwelling_type?: components["schemas"]["DwellingType"] | null;
            /** Elevator Access */
            elevator_access?: boolean | null;
            /** Floors */
            floors?: number | null;
            /** Parking Distance Feet */
            parking_distance_feet?: number | null;
            /** Stairs */
            stairs?: number | null;
        };
        /**
         * PostCallWebhookData
         * @description Allowlisted fields used from ElevenLabs post-call data.
         */
        PostCallWebhookData: {
            /** Agent Id */
            agent_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** ProvenanceReference */
        ProvenanceReference: {
            /** Excerpt */
            excerpt?: string | null;
            /** Location */
            location?: string | null;
            /** Source Id */
            source_id: string;
            source_type: components["schemas"]["ProvenanceType"];
        };
        /**
         * ProvenanceType
         * @enum {string}
         */
        ProvenanceType: "document" | "voice_intake" | "agent_tool" | "transcript" | "demo_fixture" | "tavily";
        /** QuoteV1 */
        QuoteV1: {
            /** Availability */
            availability: string;
            /** @default unknown */
            availability_status: components["schemas"]["AvailabilityStatus"];
            binding_type: components["schemas"]["BindingType"];
            /** Comparable Total */
            comparable_total?: string | null;
            /** Concessions */
            concessions?: string[];
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** Deposit */
            deposit?: string | null;
            /** Fee Line Items */
            fee_line_items: components["schemas"]["FeeLineItem"][];
            /** Findings */
            findings?: components["schemas"]["IntelligenceFinding"][];
            /** Headline Total */
            headline_total?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Job Spec Version
             * @default 1.0
             * @constant
             */
            job_spec_version: "1.0";
            /**
             * Manually Fabricated
             * @default false
             */
            manually_fabricated: boolean;
            /** Negotiated Total */
            negotiated_total?: string | null;
            /** Original Total */
            original_total?: string | null;
            /** Provenance */
            provenance?: components["schemas"]["ProvenanceReference"][];
            /** Provisional Data */
            provisional_data?: {
                [key: string]: unknown;
            };
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /**
             * Recording Url
             * Format: uri
             */
            recording_url: string;
            /** Red Flags */
            red_flags?: string[];
            /** Transcript Evidence */
            transcript_evidence?: components["schemas"]["TranscriptEvidence"][];
            vendor: components["schemas"]["Vendor"];
            verification_status: components["schemas"]["VerificationStatus"];
            /** Verified Data */
            verified_data?: {
                [key: string]: unknown;
            };
        };
        /** RecommendationRanking */
        RecommendationRanking: {
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /** Rank */
            rank: number;
            /** Rationale */
            rationale: string[];
            /** Red Flags */
            red_flags?: string[];
            /** Total */
            total?: string | null;
            vendor: components["schemas"]["Vendor"];
        };
        /** RecommendationV1 */
        RecommendationV1: {
            /** Assumptions */
            assumptions?: string[];
            /** Best Value Vendor Id */
            best_value_vendor_id?: string | null;
            /** Cheapest Vendor Id */
            cheapest_vendor_id?: string | null;
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Hidden Fee Findings */
            hidden_fee_findings?: components["schemas"]["IntelligenceFinding"][];
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Rankings */
            rankings: components["schemas"]["RecommendationRanking"][];
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
            /** Summary */
            summary: string;
            /** Transcript Evidence */
            transcript_evidence: components["schemas"]["TranscriptEvidence"][];
            /** Uncertainty */
            uncertainty?: string[];
            /**
             * Version
             * @default 1.0
             * @constant
             */
            version: "1.0";
            /**
             * Winning Vendor Id
             * Format: uuid
             */
            winning_vendor_id: string;
        };
        /**
         * RuntimeHealthResponse
         * @description Expose the selected runtime mode without revealing configuration values.
         */
        RuntimeHealthResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "live";
            /**
             * Service
             * @default veramove-api
             * @constant
             */
            service: "veramove-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** SourceContext */
        SourceContext: {
            /** Vera Property Id */
            vera_property_id?: string | null;
            /** Vera User Id */
            vera_user_id?: string | null;
        };
        /** TranscriptEvidence */
        TranscriptEvidence: {
            /**
             * Call Id
             * Format: uuid
             */
            call_id: string;
            /** Claim */
            claim: string;
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** End Seconds */
            end_seconds: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Recording Url
             * Format: uri
             */
            recording_url: string;
            /** Start Seconds */
            start_seconds: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vendor */
        Vendor: {
            /** Behavior Summary */
            behavior_summary: string;
            /** Contact Label */
            contact_label: string;
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** Name */
            name: string;
            /** Provenance */
            provenance?: components["schemas"]["ProvenanceReference"][];
            /** Service Areas */
            service_areas: string[];
            /** Slug */
            slug: string;
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
        };
        /** VendorDiscoveryResponse */
        VendorDiscoveryResponse: {
            /**
             * Source
             * @default synthetic_mock
             * @constant
             */
            source: "synthetic_mock";
            /** Vendors */
            vendors: components["schemas"]["Vendor"][];
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "provisional" | "partially_verified" | "verified" | "rejected";
        /** WebhookAck */
        WebhookAck: {
            /** Accepted */
            accepted: boolean;
            /** Duplicate */
            duplicate: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_job_from_document_api_intake_document_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSpecV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_calls_api_jobs__job_id__calls_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_job_api_jobs__job_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    negotiate_api_jobs__job_id__negotiate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_jobs__job_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_vendors_api_vendors_discover_get: {
        parameters: {
            query?: {
                origin?: string | null;
                destination?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elevenlabs_webhook_api_webhooks_elevenlabs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElevenLabsWebhookEvent"] | components["schemas"]["ElevenLabsPostCallWebhook"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"] | components["schemas"]["RuntimeHealthResponse"];
                };
            };
        };
    };
}
