/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/calls/{call_id}/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Call Recording */
        get: operations["get_call_recording_api_calls__call_id__recording_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/{call_id}/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Call */
        post: operations["repair_call_api_calls__call_id__repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intake Session By Conversation */
        get: operations["get_intake_session_by_conversation_api_intake_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job From Document */
        post: operations["create_job_from_document_api_intake_document_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Intake Session */
        post: operations["create_intake_session_api_intake_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intake Session */
        get: operations["get_intake_session_api_intake_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/sessions/{session_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Browser Voice Conversation */
        post: operations["attach_browser_voice_conversation_api_intake_sessions__session_id__conversation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/sessions/{session_id}/finish-manually": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Intake Manually */
        post: operations["finish_intake_manually_api_intake_sessions__session_id__finish_manually_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/sessions/{session_id}/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Intake Session */
        post: operations["recover_intake_session_api_intake_sessions__session_id__recover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Intake Session */
        post: operations["resume_intake_session_api_intake_sessions__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/sessions/{session_id}/voice-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Browser Voice Token */
        post: operations["issue_browser_voice_token_api_intake_sessions__session_id__voice_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration Status */
        get: operations["integration_status_api_integrations_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        /** Replace Job Spec */
        put: operations["replace_job_spec_api_jobs__job_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Calls */
        post: operations["start_calls_api_jobs__job_id__calls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Job */
        post: operations["confirm_job_api_jobs__job_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Events */
        get: operations["get_job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/negotiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Negotiate */
        post: operations["negotiate_api_jobs__job_id__negotiate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_jobs__job_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/vendor-research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vendor Research */
        get: operations["get_vendor_research_api_jobs__job_id__vendor_research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/vendor-research/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Vendor Websites */
        post: operations["analyze_vendor_websites_api_jobs__job_id__vendor_research_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/vendor-research/call-authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Authorize Vendor Calls */
        put: operations["authorize_vendor_calls_api_jobs__job_id__vendor_research_call_authorizations_put"];
        post?: never;
        /** Clear Vendor Call Authorizations */
        delete: operations["clear_vendor_call_authorizations_api_jobs__job_id__vendor_research_call_authorizations_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/vendor-research/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Vendor Contacts */
        post: operations["extract_vendor_contacts_api_jobs__job_id__vendor_research_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/vendor-research/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Job Vendors */
        post: operations["discover_job_vendors_api_jobs__job_id__vendor_research_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/vendor-research/shortlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Vendor Shortlist */
        put: operations["save_vendor_shortlist_api_jobs__job_id__vendor_research_shortlist_put"];
        post?: never;
        /** Clear Vendor Shortlist */
        delete: operations["clear_vendor_shortlist_api_jobs__job_id__vendor_research_shortlist_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover Vendors */
        get: operations["discover_vendors_api_vendors_discover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/elevenlabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Elevenlabs Webhook */
        post: operations["elevenlabs_webhook_api_webhooks_elevenlabs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/elevenlabs/pre-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Elevenlabs Conversation Initiation */
        post: operations["elevenlabs_conversation_initiation_api_webhooks_elevenlabs_pre_call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmountStatus
         * @enum {string}
         */
        AmountStatus: "known" | "unknown" | "not_applicable";
        /**
         * AttachIntakeConversationRequest
         * @description Accept only a bounded provider conversation identifier from the SDK.
         */
        AttachIntakeConversationRequest: {
            /** Conversation Id */
            conversation_id: string;
        };
        /**
         * AvailabilityStatus
         * @enum {string}
         */
        AvailabilityStatus: "available" | "unavailable" | "unknown";
        /**
         * BindingType
         * @enum {string}
         */
        BindingType: "binding" | "non_binding" | "unknown";
        /**
         * BrowserVoiceTokenResponse
         * @description Return one ephemeral token plus canonical correlation variables.
         */
        BrowserVoiceTokenResponse: {
            /** Conversation Token */
            conversation_token: string;
            dynamic_variables: components["schemas"]["IntakeDynamicVariables"];
        };
        /** CallOutcome */
        CallOutcome: {
            /** Callback At */
            callback_at?: string | null;
            quote?: components["schemas"]["QuoteV1"] | null;
            /** Reason */
            reason?: string | null;
            type: components["schemas"]["CallOutcomeType"];
        };
        /**
         * CallOutcomeType
         * @enum {string}
         */
        CallOutcomeType: "itemized_quote" | "callback_commitment" | "documented_decline" | "failed";
        /** CallRecord */
        CallRecord: {
            /**
             * Call Id
             * Format: uuid
             */
            call_id: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            outcome: components["schemas"]["CallOutcome"];
            /** Recording Url */
            recording_url?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["CallStatus"];
            vendor: components["schemas"]["Vendor"];
        };
        /**
         * CallStatus
         * @enum {string}
         */
        CallStatus: "pending" | "in_progress" | "completed" | "failed";
        /**
         * ConsentMethod
         * @description Reviewed evidence types that can establish current recipient consent.
         * @enum {string}
         */
        ConsentMethod: "direct_recipient_opt_in" | "existing_business_relationship_confirmation" | "provider_test_destination";
        /**
         * CreateIntakeSessionRequest
         * @description Select the privacy boundary before creating a browser voice session.
         */
        CreateIntakeSessionRequest: {
            /** @default supervised_role_play */
            data_mode: components["schemas"]["IntakeDataMode"];
        };
        /**
         * DataClassification
         * @enum {string}
         */
        DataClassification: "synthetic" | "role_play" | "real_redacted";
        /**
         * DocumentIntakeRequest
         * @description Bound the unstructured document text accepted by the intake route.
         */
        DocumentIntakeRequest: {
            /** Document Text */
            document_text: string;
        };
        /**
         * DwellingType
         * @enum {string}
         */
        DwellingType: "apartment" | "condo" | "townhouse" | "house" | "storage_unit" | "other";
        /**
         * ElevenLabsConversationInitiationResponse
         * @description Exact ElevenLabs response envelope for inbound personalization.
         */
        ElevenLabsConversationInitiationResponse: {
            dynamic_variables: components["schemas"]["IntakeDynamicVariables"];
            /**
             * Type
             * @default conversation_initiation_client_data
             * @constant
             */
            type: "conversation_initiation_client_data";
        };
        /**
         * ElevenLabsPostCallWebhook
         * @description Typed public shape for the ElevenLabs post-call webhook.
         */
        ElevenLabsPostCallWebhook: {
            data: components["schemas"]["PostCallWebhookData"];
            /** Event Timestamp */
            event_timestamp: number;
            /**
             * Type
             * @constant
             */
            type: "post_call_transcription";
        } & {
            [key: string]: unknown;
        };
        /** ElevenLabsWebhookEvent */
        ElevenLabsWebhookEvent: {
            /**
             * Call Id
             * @default null
             */
            call_id: string | null;
            /** Event Type */
            event_type: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * FeeCategory
         * @enum {string}
         */
        FeeCategory: "base_service" | "hourly_minimum" | "travel" | "fuel" | "stairs" | "elevator" | "long_carry" | "packing" | "materials" | "disassembly" | "storage" | "insurance" | "tax" | "deposit" | "other";
        /** FeeLineItem */
        FeeLineItem: {
            /** Amount */
            amount?: string | null;
            /** @default known */
            amount_status: components["schemas"]["AmountStatus"];
            category: components["schemas"]["FeeCategory"];
            /** Description */
            description: string;
            /**
             * Disclosed Upfront
             * @default true
             */
            disclosed_upfront: boolean;
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * Mandatory
             * @default false
             */
            mandatory: boolean;
            /** Minimum Units */
            minimum_units?: string | null;
            /** Unit Rate */
            unit_rate?: string | null;
            /** Units */
            units?: string | null;
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "info" | "warning" | "critical";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Mode
             * @default mock
             * @constant
             */
            mode: "mock";
            /**
             * Service
             * @default veramove-api
             * @constant
             */
            service: "veramove-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * IntakeDataMode
         * @description Explicit privacy boundary selected before starting a browser interview.
         * @enum {string}
         */
        IntakeDataMode: "supervised_role_play" | "real_redacted";
        /**
         * IntakeDynamicVariables
         * @description The complete custom-variable set defined by the Intake agent.
         */
        IntakeDynamicVariables: {
            /** Agent Config Version */
            agent_config_version: string;
            intake_data_mode: components["schemas"]["IntakeDataMode"];
            /**
             * Intake Session Id
             * Format: uuid
             */
            intake_session_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Missing Fields Json
             * @default []
             */
            missing_fields_json: string;
            /**
             * Partial Job Spec Json
             * @default {}
             */
            partial_job_spec_json: string;
            /**
             * Resume Mode
             * @default fresh
             * @enum {string}
             */
            resume_mode: "fresh" | "structured_partial";
        };
        /**
         * IntakeRecoveryAction
         * @description The one terminal action claimed by an incomplete intake.
         * @enum {string}
         */
        IntakeRecoveryAction: "resume" | "manual";
        /**
         * IntakeSessionResponse
         * @description Expose safe intake correlation and the result only after completion.
         */
        IntakeSessionResponse: {
            /** Conversation Id */
            conversation_id?: string | null;
            data_mode: components["schemas"]["IntakeDataMode"];
            /**
             * Intake Session Id
             * Format: uuid
             */
            intake_session_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            job_spec?: components["schemas"]["JobSpecV1"] | null;
            /**
             * Missing Fields
             * @default []
             */
            missing_fields: string[];
            partial_job_spec?: components["schemas"]["JobSpecV1"] | null;
            recovery_action?: components["schemas"]["IntakeRecoveryAction"] | null;
            /**
             * Recovery Available
             * @default false
             */
            recovery_available: boolean;
            /** Recovery Target Id */
            recovery_target_id?: string | null;
            /** Resumed From Session Id */
            resumed_from_session_id?: string | null;
            status: components["schemas"]["IntakeSessionStatus"];
            /** Terminal Reason */
            terminal_reason?: string | null;
        };
        /**
         * IntakeSessionStatus
         * @description Lifecycle of provider correlation before a normal JobRecord exists.
         * @enum {string}
         */
        IntakeSessionStatus: "pending" | "in_progress" | "incomplete" | "completed" | "failed";
        /**
         * IntakeSource
         * @enum {string}
         */
        IntakeSource: "voice" | "document" | "merged" | "demo";
        /**
         * IntegrationStatusSnapshot
         * @description Safe public status shape for all independently configured integrations.
         */
        IntegrationStatusSnapshot: {
            live_voice: components["schemas"]["ProviderIntegrationStatus"];
            openai: components["schemas"]["OpenAIIntegrationStatus"];
            supabase: components["schemas"]["ProviderIntegrationStatus"];
            tavily: components["schemas"]["ProviderIntegrationStatus"];
        };
        /** IntelligenceFinding */
        IntelligenceFinding: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /**
             * Deterministic
             * @default true
             */
            deterministic: boolean;
            /** Evidence Ids */
            evidence_ids?: string[];
            fee_category?: components["schemas"]["FeeCategory"] | null;
            /** Quote Id */
            quote_id?: string | null;
            severity: components["schemas"]["FindingSeverity"];
            /** Vendor Id */
            vendor_id?: string | null;
        };
        /** InventoryItem */
        InventoryItem: {
            /**
             * Fragile
             * @default false
             */
            fragile: boolean;
            /**
             * Item Id
             * Format: uuid
             */
            item_id?: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Oversized
             * @default false
             */
            oversized: boolean;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Room */
            room: string;
        };
        /**
         * JobEvent
         * @description Safe provider-neutral event exposed by orchestration.
         */
        JobEvent: {
            /** Call Id */
            call_id?: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id?: string;
            /** Event Type */
            event_type: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Metadata */
            metadata?: {
                [key: string]: string | number | boolean | null;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * JobEventsResponse
         * @description Envelope safe normalized events for a single job.
         */
        JobEventsResponse: {
            /** Events */
            events: components["schemas"]["JobEvent"][];
        };
        /** JobRecord */
        JobRecord: {
            /** Calls */
            calls?: components["schemas"]["CallRecord"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            job_spec: components["schemas"]["JobSpecV1"];
            /** Quotes */
            quotes?: components["schemas"]["QuoteV1"][];
            recommendation?: components["schemas"]["RecommendationV1"] | null;
            state: components["schemas"]["JobState"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobSpecV1 */
        JobSpecV1: {
            /** Bedroom Count */
            bedroom_count?: number | null;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Confirmed At */
            confirmed_at?: string | null;
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** Date Flexible */
            date_flexible?: boolean | null;
            destination: components["schemas"]["OriginDestinationAccess"];
            /** Insurance Preference */
            insurance_preference?: string | null;
            intake_source: components["schemas"]["IntakeSource"];
            /** Inventory */
            inventory?: components["schemas"]["InventoryItem"][];
            /**
             * Job Id
             * Format: uuid
             */
            job_id?: string;
            /** Locked Version */
            locked_version?: "1.0" | null;
            /** Move Date */
            move_date?: string | null;
            origin: components["schemas"]["OriginDestinationAccess"];
            /** Oversized Or Fragile Items */
            oversized_or_fragile_items?: string[];
            services?: components["schemas"]["MovingServices"];
            source_context?: components["schemas"]["SourceContext"];
            /**
             * Version
             * @default 1.0
             * @constant
             */
            version: "1.0";
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "draft" | "intake_complete" | "confirmed" | "calling" | "quotes_ready" | "negotiating" | "completed" | "failed";
        /**
         * JobVendorResearchViewV1
         * @description API-safe research state enriched from protected authorization storage.
         */
        JobVendorResearchViewV1: {
            /**
             * Authorization Ready
             * @default false
             */
            authorization_ready: boolean;
            /** Call Authorizations */
            call_authorizations?: components["schemas"]["VendorCallAuthorizationSummaryV1"][];
            /** Call Plans */
            call_plans?: components["schemas"]["VendorCallPlanV1"][];
            /** Candidates */
            candidates: components["schemas"]["Vendor"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dossiers */
            dossiers?: components["schemas"]["VendorResearchDossierV1"][];
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Job Spec Version
             * @constant
             */
            job_spec_version: "1.0";
            query: components["schemas"]["VendorSearchQuery"];
            /** Selected Vendor Ids */
            selected_vendor_ids?: string[];
            /**
             * Source
             * @enum {string}
             */
            source: "tavily" | "synthetic_mock";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MovingServices */
        MovingServices: {
            /** Disassembly */
            disassembly?: boolean | null;
            /** Packing */
            packing?: boolean | null;
            /** Storage */
            storage?: boolean | null;
            /** Storage Days */
            storage_days?: number | null;
        };
        /**
         * OpenAIIntegrationStatus
         * @description OpenAI state plus grouped, content-free usage measurements.
         */
        OpenAIIntegrationStatus: {
            /** Configured */
            configured: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Usage
             * @default []
             */
            usage: components["schemas"]["UsageAggregate"][];
        };
        /** OriginDestinationAccess */
        OriginDestinationAccess: {
            /** Access Notes */
            access_notes?: string | null;
            /** Address Summary */
            address_summary?: string | null;
            dwelling_type?: components["schemas"]["DwellingType"] | null;
            /** Elevator Access */
            elevator_access?: boolean | null;
            /** Floors */
            floors?: number | null;
            /** Parking Distance Feet */
            parking_distance_feet?: number | null;
            /** Stairs */
            stairs?: number | null;
        };
        /**
         * PostCallWebhookData
         * @description Allowlisted fields used from ElevenLabs post-call data.
         */
        PostCallWebhookData: {
            /** Agent Id */
            agent_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** ProvenanceReference */
        ProvenanceReference: {
            /** Excerpt */
            excerpt?: string | null;
            /** Location */
            location?: string | null;
            /** Source Id */
            source_id: string;
            source_type: components["schemas"]["ProvenanceType"];
        };
        /**
         * ProvenanceType
         * @enum {string}
         */
        ProvenanceType: "document" | "voice_intake" | "agent_tool" | "transcript" | "demo_fixture" | "tavily";
        /**
         * ProviderIntegrationStatus
         * @description Boolean-only state that cannot reveal provider configuration values.
         */
        ProviderIntegrationStatus: {
            /** Configured */
            configured: boolean;
            /** Enabled */
            enabled: boolean;
        };
        /** QuoteV1 */
        QuoteV1: {
            /** Availability */
            availability: string;
            /** @default unknown */
            availability_status: components["schemas"]["AvailabilityStatus"];
            binding_type: components["schemas"]["BindingType"];
            /** Comparable Total */
            comparable_total?: string | null;
            /** Concessions */
            concessions?: string[];
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** Deposit */
            deposit?: string | null;
            /** Fee Line Items */
            fee_line_items: components["schemas"]["FeeLineItem"][];
            /** Findings */
            findings?: components["schemas"]["IntelligenceFinding"][];
            /** Headline Total */
            headline_total?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Job Spec Version
             * @default 1.0
             * @constant
             */
            job_spec_version: "1.0";
            /**
             * Manually Fabricated
             * @default false
             */
            manually_fabricated: boolean;
            /** Negotiated Total */
            negotiated_total?: string | null;
            /** Original Total */
            original_total?: string | null;
            /** Provenance */
            provenance?: components["schemas"]["ProvenanceReference"][];
            /** Provisional Data */
            provisional_data?: {
                [key: string]: unknown;
            };
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /**
             * Recording Url
             * Format: uri
             */
            recording_url: string;
            /** Red Flags */
            red_flags?: string[];
            /** Transcript Evidence */
            transcript_evidence?: components["schemas"]["TranscriptEvidence"][];
            vendor: components["schemas"]["Vendor"];
            verification_status: components["schemas"]["VerificationStatus"];
            /** Verified Data */
            verified_data?: {
                [key: string]: unknown;
            };
        };
        /** RecommendationRanking */
        RecommendationRanking: {
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /** Rank */
            rank: number;
            /** Rationale */
            rationale: string[];
            /** Red Flags */
            red_flags?: string[];
            /** Total */
            total?: string | null;
            vendor: components["schemas"]["Vendor"];
        };
        /** RecommendationV1 */
        RecommendationV1: {
            /** Assumptions */
            assumptions?: string[];
            /** Best Value Vendor Id */
            best_value_vendor_id?: string | null;
            /** Cheapest Vendor Id */
            cheapest_vendor_id?: string | null;
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Hidden Fee Findings */
            hidden_fee_findings?: components["schemas"]["IntelligenceFinding"][];
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Rankings */
            rankings: components["schemas"]["RecommendationRanking"][];
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
            /** Summary */
            summary: string;
            /** Transcript Evidence */
            transcript_evidence: components["schemas"]["TranscriptEvidence"][];
            /** Uncertainty */
            uncertainty?: string[];
            /**
             * Version
             * @default 1.0
             * @constant
             */
            version: "1.0";
            /**
             * Winning Vendor Id
             * Format: uuid
             */
            winning_vendor_id: string;
        };
        /**
         * RuntimeHealthResponse
         * @description Expose the selected runtime mode without revealing configuration values.
         */
        RuntimeHealthResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "live";
            /**
             * Service
             * @default veramove-api
             * @constant
             */
            service: "veramove-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** SourceContext */
        SourceContext: {
            /** Vera Property Id */
            vera_property_id?: string | null;
            /** Vera User Id */
            vera_user_id?: string | null;
        };
        /** TranscriptEvidence */
        TranscriptEvidence: {
            /**
             * Call Id
             * Format: uuid
             */
            call_id: string;
            /** Claim */
            claim: string;
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** End Seconds */
            end_seconds: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Recording Url
             * Format: uri
             */
            recording_url: string;
            /** Start Seconds */
            start_seconds: string;
        };
        /**
         * UsageAggregate
         * @description Safe grouped usage returned by the integration-status API.
         */
        UsageAggregate: {
            /**
             * Capability
             * @enum {string}
             */
            capability: "document_extraction" | "recommendation_narration" | "vendor_website_research";
            /** Failed Requests */
            failed_requests: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Request Count */
            request_count: number;
            /** Successful Requests */
            successful_requests: number;
            /** Total Latency Ms */
            total_latency_ms: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vendor */
        Vendor: {
            /** Behavior Summary */
            behavior_summary: string;
            /** Contact Label */
            contact_label: string;
            /** @default synthetic */
            data_classification: components["schemas"]["DataClassification"];
            /** Name */
            name: string;
            /** Provenance */
            provenance?: components["schemas"]["ProvenanceReference"][];
            /** Service Areas */
            service_areas: string[];
            /** Slug */
            slug: string;
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
        };
        /**
         * VendorCallAuthorizationRequest
         * @description Exactly-three reviewed consent selections; arbitrary phone input is impossible.
         */
        VendorCallAuthorizationRequest: {
            /**
             * Batch Acknowledged
             * @constant
             */
            batch_acknowledged: true;
            /** Selections */
            selections: components["schemas"]["VendorCallAuthorizationSelectionV1"][];
        };
        /**
         * VendorCallAuthorizationSelectionV1
         * @description Browser-safe consent input referencing one server-issued contact only.
         */
        VendorCallAuthorizationSelectionV1: {
            /**
             * Ai Call Consented
             * @constant
             */
            ai_call_consented: true;
            /** Consent Evidence Reference */
            consent_evidence_reference: string;
            consent_method: components["schemas"]["ConsentMethod"];
            /**
             * Consented At
             * Format: date-time
             */
            consented_at: string;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /** Recipient Timezone */
            recipient_timezone: string;
            /**
             * Recording Consented
             * @constant
             */
            recording_consented: true;
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
        };
        /**
         * VendorCallAuthorizationSummaryV1
         * @description Public readiness view with no raw destination or suppression hash.
         */
        VendorCallAuthorizationSummaryV1: {
            /**
             * Authorization Id
             * Format: uuid
             */
            authorization_id: string;
            /** Blocking Reason */
            blocking_reason?: ("authorization_expired" | "contact_mismatch" | "outside_call_window" | "suppressed") | null;
            consent_method: components["schemas"]["ConsentMethod"];
            /**
             * Consented At
             * Format: date-time
             */
            consented_at: string;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /** Display Number */
            display_number: string;
            /** Ready */
            ready: boolean;
            /** Recipient Timezone */
            recipient_timezone: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
        };
        /**
         * VendorCallPlanQuestionV1
         * @description One targeted question copied from the deterministic verification plan.
         */
        VendorCallPlanQuestionV1: {
            /** Category */
            category: string;
            /** Claim Ids */
            claim_ids?: string[];
            /** Question */
            question: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "published_claim" | "missing_information" | "ambiguous_claim";
        };
        /**
         * VendorCallPlanV1
         * @description Deterministic, capped quote-call agenda for one locked JobSpec.
         */
        VendorCallPlanV1: {
            /** Job Spec Sha256 */
            job_spec_sha256: string;
            /**
             * Job Spec Version
             * @constant
             */
            job_spec_version: "1.0";
            /**
             * Plan Version
             * @default 1.0
             * @constant
             */
            plan_version: "1.0";
            /** Questions */
            questions: components["schemas"]["VendorCallPlanQuestionV1"][];
            /** Source Urls */
            source_urls?: string[];
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
            /** Website Claims */
            website_claims?: components["schemas"]["VendorCallPlanWebsiteClaimV1"][];
        };
        /**
         * VendorCallPlanWebsiteClaimV1
         * @description A bounded unverified website claim supplied as call context, never evidence.
         */
        VendorCallPlanWebsiteClaimV1: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /**
             * Classification
             * @default unverified_website_claim
             * @constant
             */
            classification: "unverified_website_claim";
            /** Kind */
            kind: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Summary */
            summary: string;
        };
        /**
         * VendorContactCandidateV1
         * @description One official-site public business contact with tamper-evident provenance.
         */
        VendorContactCandidateV1: {
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id?: string;
            /** Display Number */
            display_number: string;
            /** Source Excerpt */
            source_excerpt: string;
            /** Source Excerpt Sha256 */
            source_excerpt_sha256: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
        };
        /** VendorDiscoveryResponse */
        VendorDiscoveryResponse: {
            /**
             * Source
             * @enum {string}
             */
            source: "synthetic_mock" | "tavily";
            /** Vendors */
            vendors: components["schemas"]["Vendor"][];
        };
        /**
         * VendorResearchDossierV1
         * @description Persisted website research for one selected real or synthetic vendor.
         */
        VendorResearchDossierV1: {
            /** Claims */
            claims?: components["schemas"]["WebsiteResearchClaimV1"][];
            /** Contact Candidates */
            contact_candidates?: components["schemas"]["VendorContactCandidateV1"][];
            /** Missing Fee Categories */
            missing_fee_categories?: components["schemas"]["FeeCategory"][];
            /** Researched At */
            researched_at?: string | null;
            /** Safe Failure Reason */
            safe_failure_reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "complete" | "partial" | "failed";
            vendor: components["schemas"]["Vendor"];
            /** Verification Questions */
            verification_questions?: components["schemas"]["VendorVerificationQuestionV1"][];
        };
        /** VendorSearchQuery */
        VendorSearchQuery: {
            /** City */
            city: string;
            /**
             * Radius Miles
             * @default 25
             */
            radius_miles: number;
            /**
             * Service Type
             * @default moving
             */
            service_type: string;
            /** State */
            state: string;
        };
        /**
         * VendorShortlistRequest
         * @description Browser request containing IDs only, never Vendor objects or URLs.
         */
        VendorShortlistRequest: {
            /** Vendor Ids */
            vendor_ids: string[];
        };
        /**
         * VendorVerificationQuestionV1
         * @description One deterministic future-call question derived from claims or omissions.
         */
        VendorVerificationQuestionV1: {
            /** Category */
            category: components["schemas"]["FeeCategory"] | components["schemas"]["WebsiteClaimKind"];
            /** Claim Ids */
            claim_ids?: string[];
            /** Question */
            question: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id?: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "published_claim" | "missing_information" | "ambiguous_claim";
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "provisional" | "partially_verified" | "verified" | "rejected";
        /** WebhookAck */
        WebhookAck: {
            /** Accepted */
            accepted: boolean;
            /** Duplicate */
            duplicate: boolean;
        };
        /**
         * WebsiteClaimKind
         * @description Allowed website statements; fee values intentionally mirror FeeCategory.
         * @enum {string}
         */
        WebsiteClaimKind: "base_service" | "hourly_minimum" | "travel" | "fuel" | "stairs" | "elevator" | "long_carry" | "packing" | "materials" | "disassembly" | "storage" | "insurance" | "tax" | "deposit" | "other" | "hourly_rate" | "minimum_hours" | "mover_count" | "service" | "availability" | "binding";
        /**
         * WebsiteResearchClaimV1
         * @description One bounded webpage-supported statement that is never call evidence.
         */
        WebsiteResearchClaimV1: {
            /** Advertised Amount */
            advertised_amount?: string | null;
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id?: string;
            /**
             * Classification
             * @default unverified_website_claim
             * @constant
             */
            classification: "unverified_website_claim";
            /** Currency */
            currency?: string | null;
            kind: components["schemas"]["WebsiteClaimKind"];
            /** Qualifiers */
            qualifiers?: string[];
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Excerpt */
            source_excerpt: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Summary */
            summary: string;
            /** Unit */
            unit?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_call_recording_api_calls__call_id__recording_get: {
        parameters: {
            query: {
                job_id: string;
                signature: string;
            };
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validated provider recording audio. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mp4": unknown;
                    "audio/mpeg": unknown;
                    "audio/wav": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_call_api_calls__call_id__repair_post: {
        parameters: {
            query?: never;
            header?: {
                "x-veramove-operator-secret"?: string | null;
            };
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intake_session_by_conversation_api_intake_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_from_document_api_intake_document_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intake_session_api_intake_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateIntakeSessionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intake_session_api_intake_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_browser_voice_conversation_api_intake_sessions__session_id__conversation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachIntakeConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_intake_manually_api_intake_sessions__session_id__finish_manually_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recover_intake_session_api_intake_sessions__session_id__recover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_intake_session_api_intake_sessions__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_browser_voice_token_api_intake_sessions__session_id__voice_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserVoiceTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integration_status_api_integrations_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusSnapshot"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSpecV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_job_spec_api_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSpecV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_calls_api_jobs__job_id__calls_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_job_api_jobs__job_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    negotiate_api_jobs__job_id__negotiate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_jobs__job_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vendor_research_api_jobs__job_id__vendor_research_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_vendor_websites_api_jobs__job_id__vendor_research_analyze_post: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_vendor_calls_api_jobs__job_id__vendor_research_call_authorizations_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorCallAuthorizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_vendor_call_authorizations_api_jobs__job_id__vendor_research_call_authorizations_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_vendor_contacts_api_jobs__job_id__vendor_research_contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_job_vendors_api_jobs__job_id__vendor_research_discover_post: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_vendor_shortlist_api_jobs__job_id__vendor_research_shortlist_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorShortlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_vendor_shortlist_api_jobs__job_id__vendor_research_shortlist_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVendorResearchViewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_vendors_api_vendors_discover_get: {
        parameters: {
            query?: {
                origin?: string | null;
                destination?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elevenlabs_webhook_api_webhooks_elevenlabs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElevenLabsWebhookEvent"] | components["schemas"]["ElevenLabsPostCallWebhook"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
        };
    };
    elevenlabs_conversation_initiation_api_webhooks_elevenlabs_pre_call_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Agent Id */
                    agent_id: string;
                    /** Call Sid */
                    call_sid: string;
                    /** Called Number */
                    called_number?: string | null;
                    /** Caller Id */
                    caller_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElevenLabsConversationInitiationResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"] | components["schemas"]["RuntimeHealthResponse"];
                };
            };
        };
    };
}
